"""empty message

Revision ID: 14a40e67ce43
Revises: ff6c19485ed7
Create Date: 2025-07-22 00:30:30.918191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a40e67ce43'
down_revision = 'ff6c19485ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batchNo', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['batchNo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('batchNo')

    # ### end Alembic commands ###
