"""empty message

Revision ID: 1704d2eeadf8
Revises: 656c46418ff4
Create Date: 2025-08-31 16:51:44.924556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1704d2eeadf8'
down_revision = '656c46418ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordermedicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medicineName', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordermedicine', schema=None) as batch_op:
        batch_op.drop_column('medicineName')

    # ### end Alembic commands ###
