"""empty message

Revision ID: 30b9df05da0c
Revises: 9cda1260bf3b
Create Date: 2025-07-31 19:17:32.722421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b9df05da0c'
down_revision = '9cda1260bf3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.drop_column('medicineQuantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medicineQuantity', sa.INTEGER(), nullable=False))
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
