"""empty message

Revision ID: 341ac3baa73f
Revises: 49d9e67673a4
Create Date: 2025-07-22 18:07:41.201937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341ac3baa73f'
down_revision = '49d9e67673a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufactureDate', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_column('manufactureDate')

    # ### end Alembic commands ###
