"""empty message

Revision ID: 3a7e60433c18
Revises: 1704d2eeadf8
Create Date: 2025-08-31 17:12:11.797225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7e60433c18'
down_revision = '1704d2eeadf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordermedicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalPrice', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('pricePerUnit', sa.String(), nullable=False))
        batch_op.drop_column('price')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('billAmount',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('billAmount',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('ordermedicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=False))
        batch_op.drop_column('pricePerUnit')
        batch_op.drop_column('totalPrice')

    # ### end Alembic commands ###
