"""empty message

Revision ID: 49d9e67673a4
Revises: b176dfde3391
Create Date: 2025-07-22 17:10:56.852511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d9e67673a4'
down_revision = 'b176dfde3391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['batchNo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
