"""empty message

Revision ID: 5779d8a6f960
Revises: c96661830159
Create Date: 2025-07-17 23:17:50.200116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5779d8a6f960'
down_revision = 'c96661830159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contactNumber', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('contactNumber')

    # ### end Alembic commands ###
