"""empty message

Revision ID: 5f91cf9144de
Revises: 5779d8a6f960
Create Date: 2025-07-19 21:37:38.943713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f91cf9144de'
down_revision = '5779d8a6f960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contactNumber', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('specialization', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('specialization')
        batch_op.drop_column('contactNumber')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
