"""empty message

Revision ID: 605ca1bea9f4
Revises: cdc444a92daa
Create Date: 2025-07-31 19:48:49.174513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605ca1bea9f4'
down_revision = 'cdc444a92daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('purchaseId', sa.Integer(), nullable=False),
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('purchaseId')
    )
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['batchNo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('purchase')
    # ### end Alembic commands ###
