"""empty message

Revision ID: 60a9facfe68d
Revises: 
Create Date: 2025-07-09 16:55:42.573999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a9facfe68d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemist',
    sa.Column('chemistId', sa.Integer(), nullable=False),
    sa.Column('shopname', sa.String(), nullable=False),
    sa.Column('chemistName', sa.String(), nullable=False),
    sa.Column('chemistEmail', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('chemistId'),
    sa.UniqueConstraint('chemistEmail')
    )
    op.create_table('doctor',
    sa.Column('doctorId', sa.Integer(), nullable=False),
    sa.Column('hospitalname', sa.String(), nullable=False),
    sa.Column('doctorName', sa.String(), nullable=False),
    sa.Column('doctorEmail', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('doctorId'),
    sa.UniqueConstraint('doctorEmail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor')
    op.drop_table('chemist')
    # ### end Alembic commands ###
