"""empty message

Revision ID: 654d6f12392c
Revises: c6549d84e216
Create Date: 2025-07-22 00:23:44.927353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654d6f12392c'
down_revision = 'c6549d84e216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batchNo', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['batchNo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('batchNo')

    # ### end Alembic commands ###
