"""empty message

Revision ID: 656c46418ff4
Revises: 7e1607c4e415
Create Date: 2025-08-29 22:52:47.545145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656c46418ff4'
down_revision = '7e1607c4e415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemist', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('chemist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
