"""empty message

Revision ID: 67f9f6af8978
Revises: e3ded4a46c44
Create Date: 2025-08-26 21:56:37.401996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f9f6af8978'
down_revision = 'e3ded4a46c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('medicineId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('doctorId', sa.Integer(), nullable=False),
    sa.Column('orderDate', sa.Date(), nullable=False),
    sa.Column('chemistId', sa.Integer(), nullable=False),
    sa.Column('billAmount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('orderId')
    )
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'chemist', ['chemistId'], ['chemistId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('orders')
    op.drop_table('order_medicine')
    # ### end Alembic commands ###
