"""empty message

Revision ID: 6c8709ae2749
Revises: d92cbaa47681
Create Date: 2025-08-31 18:09:48.714380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8709ae2749'
down_revision = 'd92cbaa47681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordermedicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('medicineId', sa.Integer(), nullable=False),
    sa.Column('medicineName', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('totalPrice', sa.String(), nullable=False),
    sa.Column('pricePerUnit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('doctorId', sa.Integer(), nullable=False),
    sa.Column('orderDate', sa.Date(), nullable=False),
    sa.Column('chemistId', sa.Integer(), nullable=False),
    sa.Column('billAmount', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('orderId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('ordermedicine')
    # ### end Alembic commands ###
