"""empty message

Revision ID: 7981b1676cd9
Revises: bf8a6b548045
Create Date: 2025-07-31 19:28:05.844480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7981b1676cd9'
down_revision = 'bf8a6b548045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('medicineId', sa.Integer(), nullable=False),
    sa.Column('medicineName', sa.String(), nullable=False),
    sa.Column('batchNo', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('medicinePrice', sa.String(), nullable=False),
    sa.Column('companyName', sa.String(), nullable=False),
    sa.Column('expiryDate', sa.Date(), nullable=False),
    sa.Column('manufactureDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('medicineId')
    )
    op.drop_table('medicine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
    sa.Column('medicineId', sa.INTEGER(), nullable=False),
    sa.Column('medicineName', sa.VARCHAR(), nullable=False),
    sa.Column('medicinePrice', sa.VARCHAR(), nullable=False),
    sa.Column('companyName', sa.VARCHAR(), nullable=False),
    sa.Column('expiryDate', sa.DATE(), nullable=False),
    sa.Column('batchNo', sa.VARCHAR(), nullable=False),
    sa.Column('manufactureDate', sa.DATE(), nullable=False),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('medicineId')
    )
    op.drop_table('medicines')
    # ### end Alembic commands ###
