"""empty message

Revision ID: 7be9aae79a61
Revises: b17bc778bc38
Create Date: 2025-08-02 12:57:02.675378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be9aae79a61'
down_revision = 'b17bc778bc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('customerEmail', sa.String(), nullable=False),
    sa.Column('customerName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('customerId')
    )
    op.create_table('purchase',
    sa.Column('purchaseId', sa.Integer(), nullable=False),
    sa.Column('billId', sa.Integer(), nullable=False),
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('billAmount', sa.Integer(), nullable=False),
    sa.Column('chemistId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('purchaseId')
    )
    op.create_table('sales',
    sa.Column('salesId', sa.Integer(), nullable=False),
    sa.Column('billId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('pricePerUnit', sa.String(), nullable=False),
    sa.Column('totalPrice', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('chemistId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('salesId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('purchase')
    op.drop_table('customers')
    # ### end Alembic commands ###
