"""empty message

Revision ID: 7e1607c4e415
Revises: c08caa340e67
Create Date: 2025-08-27 23:23:54.398020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1607c4e415'
down_revision = 'c08caa340e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(), nullable=True))

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(), nullable=True))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('chemist', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
