"""empty message

Revision ID: 845cd8ecbf0a
Revises: a2ba3de56bf1
Create Date: 2025-09-04 12:10:01.144221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845cd8ecbf0a'
down_revision = 'a2ba3de56bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('appointmentId', sa.INTEGER(), nullable=False),
    sa.Column('doctorId', sa.INTEGER(), nullable=False),
    sa.Column('appointmentDate', sa.DATE(), nullable=True),
    sa.Column('patientId', sa.INTEGER(), nullable=False),
    sa.Column('appointmentTime', sa.VARCHAR(), nullable=True),
    sa.Column('patientType', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('appointmentId')
    )
    # ### end Alembic commands ###
