"""empty message

Revision ID: 8f0fd00c579c
Revises: 5f91cf9144de
Create Date: 2025-07-19 23:26:55.193261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0fd00c579c'
down_revision = '5f91cf9144de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contactNumber', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemist', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('contactNumber')

    # ### end Alembic commands ###
