"""empty message

Revision ID: 8f1985aa5599
Revises: 845cd8ecbf0a
Create Date: 2025-09-04 12:10:23.127035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1985aa5599'
down_revision = '845cd8ecbf0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('appointmentId', sa.Integer(), nullable=False),
    sa.Column('doctorId', sa.Integer(), nullable=False),
    sa.Column('appointmentDate', sa.Date(), nullable=True),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('appointmentTime', sa.String(), nullable=True),
    sa.Column('patientType', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('appointmentId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    # ### end Alembic commands ###
