"""empty message

Revision ID: 94dd068c3fce
Revises: 7be9aae79a61
Create Date: 2025-08-03 21:09:55.493917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94dd068c3fce'
down_revision = '7be9aae79a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicines')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('medicineId', sa.INTEGER(), nullable=False),
    sa.Column('medicineName', sa.VARCHAR(), nullable=False),
    sa.Column('batchNo', sa.VARCHAR(), nullable=False),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.Column('medicinePrice', sa.VARCHAR(), nullable=False),
    sa.Column('companyName', sa.VARCHAR(), nullable=False),
    sa.Column('expiryDate', sa.DATE(), nullable=False),
    sa.Column('manufactureDate', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('medicineId')
    )
    # ### end Alembic commands ###
