"""empty message

Revision ID: 99aa1bef9e45
Revises: 91ee7a0f8d34
Create Date: 2025-07-22 00:34:19.732236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99aa1bef9e45'
down_revision = '91ee7a0f8d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batchNo', sa.String(), nullable=False))
        batch_op.create_unique_constraint('unique_batch_no', ['batchNo'])
        batch_op.create_unique_constraint(None, ['batchNo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('unique_batch_no', type_='unique')
        batch_op.drop_column('batchNo')

    # ### end Alembic commands ###
