"""empty message

Revision ID: 9cda1260bf3b
Revises: f24da96e82e3
Create Date: 2025-07-22 20:30:10.982472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cda1260bf3b'
down_revision = 'f24da96e82e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chemistId', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('chemistId')

    # ### end Alembic commands ###
