"""empty message

Revision ID: a1de6620110b
Revises: 0641154e5ced
Create Date: 2025-07-22 00:36:47.367310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1de6620110b'
down_revision = '0641154e5ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctorEmail', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['doctorEmail'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('doctorEmail')

    # ### end Alembic commands ###
