"""empty message

Revision ID: b17bc778bc38
Revises: d6caad9975bb
Create Date: 2025-08-02 12:56:29.495731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17bc778bc38'
down_revision = 'd6caad9975bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('purchase')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customerId', sa.INTEGER(), nullable=False),
    sa.Column('customerEmail', sa.VARCHAR(), nullable=False),
    sa.Column('customerName', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('customerId')
    )
    op.create_table('purchase',
    sa.Column('purchaseId', sa.INTEGER(), nullable=False),
    sa.Column('customerId', sa.INTEGER(), nullable=False),
    sa.Column('billAmount', sa.INTEGER(), nullable=False),
    sa.Column('chemistId', sa.INTEGER(), nullable=False),
    sa.Column('billId', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('purchaseId')
    )
    op.create_table('sales',
    sa.Column('salesId', sa.INTEGER(), nullable=False),
    sa.Column('billId', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('pricePerUnit', sa.VARCHAR(), nullable=False),
    sa.Column('totalPrice', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('chemistId', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('salesId')
    )
    # ### end Alembic commands ###
