"""empty message

Revision ID: bf8a6b548045
Revises: 30b9df05da0c
Create Date: 2025-07-31 19:26:46.858479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8a6b548045'
down_revision = '30b9df05da0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_medicine')
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.drop_column('medicineQuantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medicineQuantity', sa.INTEGER(), nullable=False))
        batch_op.drop_column('stock')

    op.create_table('_alembic_tmp_medicine',
    sa.Column('medicineId', sa.INTEGER(), nullable=False),
    sa.Column('medicineName', sa.VARCHAR(), nullable=False),
    sa.Column('medicinePrice', sa.VARCHAR(), nullable=False),
    sa.Column('companyName', sa.VARCHAR(), nullable=False),
    sa.Column('expiryDate', sa.DATE(), nullable=False),
    sa.Column('batchNo', sa.VARCHAR(), nullable=False),
    sa.Column('manufactureDate', sa.DATE(), nullable=False),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('medicineId')
    )
    # ### end Alembic commands ###
