"""empty message

Revision ID: c08caa340e67
Revises: 67f9f6af8978
Create Date: 2025-08-26 21:57:24.505827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08caa340e67'
down_revision = '67f9f6af8978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordermedicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('medicineId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_medicine')
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'chemist', ['chemistId'], ['chemistId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('order_medicine',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('orderId', sa.INTEGER(), nullable=False),
    sa.Column('medicineId', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ordermedicine')
    # ### end Alembic commands ###
