"""empty message

Revision ID: c6549d84e216
Revises: 8f0fd00c579c
Create Date: 2025-07-22 00:07:45.120551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6549d84e216'
down_revision = '8f0fd00c579c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
    sa.Column('medicineId', sa.Integer(), nullable=False),
    sa.Column('medicineName', sa.String(), nullable=False),
    sa.Column('medicineQuantity', sa.Integer(), nullable=False),
    sa.Column('medicinePrice', sa.Integer(), nullable=False),
    sa.Column('companyName', sa.String(), nullable=False),
    sa.Column('expiryDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('medicineId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicine')
    # ### end Alembic commands ###
