"""empty message

Revision ID: c96661830159
Revises: 60a9facfe68d
Create Date: 2025-07-16 09:38:22.620332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96661830159'
down_revision = '60a9facfe68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('patientdob', sa.Date(), nullable=False),
    sa.Column('patientName', sa.String(), nullable=False),
    sa.Column('patientEmail', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('patientId'),
    sa.UniqueConstraint('patientEmail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    # ### end Alembic commands ###
