"""empty message

Revision ID: d92cbaa47681
Revises: 3a7e60433c18
Create Date: 2025-08-31 18:09:25.807259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92cbaa47681'
down_revision = '3a7e60433c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('ordermedicine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordermedicine',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('orderId', sa.INTEGER(), nullable=False),
    sa.Column('medicineId', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('medicineName', sa.VARCHAR(), nullable=False),
    sa.Column('totalPrice', sa.VARCHAR(), nullable=False),
    sa.Column('pricePerUnit', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('orderId', sa.INTEGER(), nullable=False),
    sa.Column('doctorId', sa.INTEGER(), nullable=False),
    sa.Column('orderDate', sa.DATE(), nullable=False),
    sa.Column('chemistId', sa.INTEGER(), nullable=False),
    sa.Column('billAmount', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('orderId')
    )
    # ### end Alembic commands ###
