"""empty message

Revision ID: da8db57aab6d
Revises: 6c8709ae2749
Create Date: 2025-09-04 11:43:38.485480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8db57aab6d'
down_revision = '6c8709ae2749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patientType', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('patientType')

    # ### end Alembic commands ###
