"""empty message

Revision ID: e3ded4a46c44
Revises: 94dd068c3fce
Create Date: 2025-08-03 21:10:22.004561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ded4a46c44'
down_revision = '94dd068c3fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('medicineId', sa.Integer(), nullable=False),
    sa.Column('medicineName', sa.String(), nullable=False),
    sa.Column('batchNo', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('medicinePrice', sa.String(), nullable=False),
    sa.Column('companyName', sa.String(), nullable=False),
    sa.Column('expiryDate', sa.Date(), nullable=False),
    sa.Column('manufactureDate', sa.Date(), nullable=False),
    sa.Column('chemistId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('medicineId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicines')
    # ### end Alembic commands ###
