"""empty message

Revision ID: e61b30e374c3
Revises: 2ec02075af49
Create Date: 2025-07-31 19:58:53.255437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61b30e374c3'
down_revision = '2ec02075af49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billAmount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('chemistId', sa.Integer(), nullable=False))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('billAmount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billAmount', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('chemistId')
        batch_op.drop_column('billAmount')

    # ### end Alembic commands ###
