"""empty message

Revision ID: f045a5dbadd8
Revises: da8db57aab6d
Create Date: 2025-09-04 11:48:21.126995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f045a5dbadd8'
down_revision = 'da8db57aab6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('appointmentDate',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('appointmentTime',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('appointmentTime',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('appointmentDate',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
