"""empty message

Revision ID: f24da96e82e3
Revises: a510c3885e95
Create Date: 2025-07-22 20:24:21.361736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24da96e82e3'
down_revision = 'a510c3885e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('appointmentId', sa.Integer(), nullable=False),
    sa.Column('doctorId', sa.Integer(), nullable=False),
    sa.Column('appointmentDate', sa.Date(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('appointmentTime', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('appointmentId')
    )
    op.create_table('customers',
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('customerEmail', sa.String(), nullable=False),
    sa.Column('customerName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('customerId')
    )
    op.create_table('sales',
    sa.Column('salesId', sa.Integer(), nullable=False),
    sa.Column('billId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('pricePerUnit', sa.String(), nullable=False),
    sa.Column('totalPrice', sa.Integer(), nullable=False),
    sa.Column('billAmount', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('salesId')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('gender')

    op.drop_table('sales')
    op.drop_table('customers')
    op.drop_table('appointment')
    # ### end Alembic commands ###
